#  -*- coding: utf-8 -*-
###############################################################################
#                                                                             #
#   Ambrosia - a tool to visualize ANANAS results                             #
#                                                                             #
#     Copyright (C) 2015 Wolfgang Ettlinger and the ANANAS Team               #
#                                                                             #
#    This program is free software: you can redistribute it and/or modify     #
#    it under the terms of the GNU General Public License as published by     #
#    the Free Software Foundation, either version 3 of the License, or        #
#    (at your option) any later version.                                      #
#                                                                             #
#    This program is distributed in the hope that it will be useful,          #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
#                                                                             #
#    the ANANAS Project  Copyright (C) 2015                                   #
#                                                                             #
###############################################################################
import dateutil
import json

import ambrosia
from ambrosia import model
from ambrosia.context import AmbrosiaContext
from ambrosia.plugins import PluginInfoTop

__author__ = 'Wolfgang Ettlinger'


class PluginInfo(PluginInfoTop):
    @staticmethod
    def correlators():
        return []

    @staticmethod
    def parsers():
        return [EventParser]


class ANANASEvent(model.Event):
    """Represents an event generated by the ANANAS analysis system itself. Any action performed by ANANAS that affects
    the emulator (e.g. execution of a command) is recorded in a ANANASEvent.

    Args:
        name (str): the type of the event
        timestamp (datetime.datetime): the time the event occurred (host clock)
        params: additional parameters (any serializable data structure)
    """
    indices = {'name', 'start_ts'}

    def __init__(self, name, timestamp, params):
        super(ANANASEvent, self).__init__(start_ts=timestamp)
        self.name = name
        self.params = params
    
    def get_serializeable_properties(self):
        return {'name': self.name,
                'params': self.params}

    def __str__(self):
        return '[ANANAS Event: {} {}]'.format(self.name, json.dumps(self.params))


class EventParser(ambrosia.ResultParser):
    """ Parses the *events* xml tag
    """
    def parse(self, name, el, context):
        assert isinstance(context, AmbrosiaContext)
        if name == 'events':
            for evt in el:
                context.analysis.add_event(ANANASEvent(
                    evt.attrib['name'],
                    dateutil.parser.parse(evt.attrib['timestamp']),
                    json.loads(evt.attrib['parameters'])))




