/*{
function Property(prop, p2){
    this.prop = prop;
    this.p2 = p2;
}

function Comparison(p1, op, p2){
    this.p1 = p1;
    this.op = op;
    this.p2 = p2;
}

function Statement(p1, op, p2){
    this.p1 = p1;
    this.op = op;
    this.p2 = p2;
}

function UnaryOperator(op, ex){
    this.op = op;
    this.ex = ex;
}

}
*/

start
  = expression

expression
  = statement
  / "(" exp:expression ")" { return exp }

statement
  = c1:comparison ws op:logical_operator ws c2:statement { return new ambrosia.filter.Statement(c1, op, c2) }
  / c:comparison { return c }
  / lo:unary_operator ex:expression { return new ambrosia.filter.UnaryOperator(lo, ex); }


comparison
  = p1:value ws op:operand ws p2:value { return new ambrosia.filter.Comparison(p1, op, p2) }

value
  = property
  / string
  / number

operand
  = '==' { return 'EQ'}
  / '!=' { return 'NEQ' }
  / '>=' { return 'GE' }
  / '>' { return 'G' }
  / '<=' { return 'LE' }
  / '<' { return 'L' }
  / '~' { return 'REGEX' }
  / ':' { return 'IN' }
  / '!:' { return 'NIN' }

unary_operator
  = '!' { return 'NOT' }

logical_operator
  = op:'&&' { return 'AND'}
  / op:'||' { return 'OR' }

property
  = p1:[a-zA-Z_]+ "."? p2:[a-zA-Z_]* { return new ambrosia.filter.Property(p1.join(""), p2.join("")) }

string
  = '"' str:[^\"]* '"' { return str.join("") }

number
  = num:[0-9\.]+ { return parseFloat(num.join("")) }

ws
  = [ \t]*
